using System.Collections.Generic;
using System.Linq;
using CardRoulette.CardLib;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace CardRoulette {
	public class Bet {
		public static Texture2D Board;

		public int Amount;
		public Vector2 Position;

		public BetType Type => BetTypesDictionary[Position];
		public IEnumerable<Card> Cards => CardsDictionary[Position];

		public Bet( int amount, Vector2 position ) {
			this.Amount = amount;
			this.Position = position;
		}

		static Bet() {
			BetTypesDictionary = new Dictionary<Vector2, BetType>();
			CardsDictionary = new Dictionary<Vector2, IEnumerable<Card>>();

			FillCards();
			FillBetTypes();
		}

		private static void FillCards() {
			CardsDictionary.Add( new Vector2( 309, 339 ), Deck.PokerDeck( true ).Where( c => new[] { CardValue.BigJoker, CardValue.TwoOfSpades }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 359, 339 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.TwoOfSpades ) );
			CardsDictionary.Add( new Vector2( 409, 339 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.TwoOfSpades, CardValue.ThreeOfSpades }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 459, 339 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.ThreeOfSpades ) );
			CardsDictionary.Add( new Vector2( 509, 339 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.ThreeOfSpades, CardValue.FourOfSpades }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 559, 339 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.FourOfSpades ) );
			CardsDictionary.Add( new Vector2( 609, 339 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.FourOfSpades, CardValue.FiveOfSpades }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 659, 339 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.FiveOfSpades ) );
			CardsDictionary.Add( new Vector2( 709, 339 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.FiveOfSpades, CardValue.SixOfSpades }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 759, 339 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.SixOfSpades ) );
			CardsDictionary.Add( new Vector2( 809, 339 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.SixOfSpades, CardValue.SevenOfSpades }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 859, 339 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.SevenOfSpades ) );
			CardsDictionary.Add( new Vector2( 909, 339 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.SevenOfSpades, CardValue.EightOfSpades }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 959, 339 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.EightOfSpades ) );
			CardsDictionary.Add( new Vector2( 1009, 339 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.EightOfSpades, CardValue.NineOfSpades }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1059, 339 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.NineOfSpades ) );
			CardsDictionary.Add( new Vector2( 1109, 339 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.NineOfSpades, CardValue.TenOfSpades }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1159, 339 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.TenOfSpades ) );
			CardsDictionary.Add( new Vector2( 1209, 339 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.TenOfSpades, CardValue.JackOfSpades }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1259, 339 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.JackOfSpades ) );
			CardsDictionary.Add( new Vector2( 1309, 339 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.JackOfSpades, CardValue.QueenOfSpades }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1359, 339 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.QueenOfSpades ) );
			CardsDictionary.Add( new Vector2( 1409, 339 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.QueenOfSpades, CardValue.KingOfSpades }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1459, 339 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.KingOfSpades ) );
			CardsDictionary.Add( new Vector2( 1509, 339 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.KingOfSpades, CardValue.AceOfSpades }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1559, 339 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.AceOfSpades ) );
			CardsDictionary.Add( new Vector2( 1609, 339 ), Deck.PokerDeck( false ).Where( c => Suits.Spades == c.Value.GetSuit() ) );

			CardsDictionary.Add( new Vector2( 309, 389 ), Deck.PokerDeck( true ).Where( c => new[] { CardValue.BigJoker, CardValue.TwoOfSpades, CardValue.TwoOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 359, 389 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.TwoOfSpades, CardValue.TwoOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 409, 389 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.TwoOfSpades, CardValue.TwoOfClubs, CardValue.ThreeOfSpades, CardValue.ThreeOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 459, 389 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.ThreeOfSpades, CardValue.ThreeOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 509, 389 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.ThreeOfSpades, CardValue.ThreeOfClubs, CardValue.FourOfSpades, CardValue.FourOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 559, 389 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.FourOfSpades, CardValue.FourOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 609, 389 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.FourOfSpades, CardValue.FourOfClubs, CardValue.FiveOfSpades, CardValue.FiveOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 659, 389 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.FiveOfSpades, CardValue.FiveOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 709, 389 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.FiveOfSpades, CardValue.FiveOfClubs, CardValue.SixOfSpades, CardValue.SixOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 759, 389 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.SixOfSpades, CardValue.SixOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 809, 389 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.SixOfSpades, CardValue.SixOfClubs, CardValue.SevenOfSpades, CardValue.SevenOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 859, 389 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.SevenOfSpades, CardValue.SevenOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 909, 389 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.SevenOfSpades, CardValue.SevenOfClubs, CardValue.EightOfSpades, CardValue.EightOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 959, 389 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.EightOfSpades, CardValue.EightOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1009, 389 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.EightOfSpades, CardValue.EightOfClubs, CardValue.NineOfSpades, CardValue.NineOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1059, 389 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.NineOfSpades, CardValue.NineOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1109, 389 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.NineOfSpades, CardValue.NineOfClubs, CardValue.TenOfSpades, CardValue.TenOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1159, 389 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.TenOfSpades, CardValue.TenOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1209, 389 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.TenOfSpades, CardValue.TenOfClubs, CardValue.JackOfSpades, CardValue.JackOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1259, 389 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.JackOfSpades, CardValue.JackOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1309, 389 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.JackOfSpades, CardValue.JackOfClubs, CardValue.QueenOfSpades, CardValue.QueenOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1359, 389 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.QueenOfSpades, CardValue.QueenOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1409, 389 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.QueenOfSpades, CardValue.QueenOfClubs, CardValue.KingOfSpades, CardValue.KingOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1459, 389 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.KingOfSpades, CardValue.KingOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1509, 389 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.KingOfSpades, CardValue.KingOfClubs, CardValue.AceOfSpades, CardValue.AceOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1559, 389 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.AceOfSpades, CardValue.AceOfClubs }.Contains( c.Value ) ) );

			CardsDictionary.Add( new Vector2( 309, 439 ), Deck.PokerDeck( true ).Where( c => new[] { CardValue.BigJoker, CardValue.TwoOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 359, 439 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.TwoOfClubs ) );
			CardsDictionary.Add( new Vector2( 409, 439 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.TwoOfClubs, CardValue.ThreeOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 459, 439 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.ThreeOfClubs ) );
			CardsDictionary.Add( new Vector2( 509, 439 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.ThreeOfClubs, CardValue.FourOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 559, 439 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.FourOfClubs ) );
			CardsDictionary.Add( new Vector2( 609, 439 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.FourOfClubs, CardValue.FiveOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 659, 439 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.FiveOfClubs ) );
			CardsDictionary.Add( new Vector2( 709, 439 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.FiveOfClubs, CardValue.SixOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 759, 439 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.SixOfClubs ) );
			CardsDictionary.Add( new Vector2( 809, 439 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.SixOfClubs, CardValue.SevenOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 859, 439 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.SevenOfClubs ) );
			CardsDictionary.Add( new Vector2( 909, 439 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.SevenOfClubs, CardValue.EightOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 959, 439 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.EightOfClubs ) );
			CardsDictionary.Add( new Vector2( 1009, 439 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.EightOfClubs, CardValue.NineOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1059, 439 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.NineOfClubs ) );
			CardsDictionary.Add( new Vector2( 1109, 439 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.NineOfClubs, CardValue.TenOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1159, 439 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.TenOfClubs ) );
			CardsDictionary.Add( new Vector2( 1209, 439 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.TenOfClubs, CardValue.JackOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1259, 439 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.JackOfClubs ) );
			CardsDictionary.Add( new Vector2( 1309, 439 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.JackOfClubs, CardValue.QueenOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1359, 439 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.QueenOfClubs ) );
			CardsDictionary.Add( new Vector2( 1409, 439 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.QueenOfClubs, CardValue.KingOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1459, 439 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.KingOfClubs ) );
			CardsDictionary.Add( new Vector2( 1509, 439 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.KingOfClubs, CardValue.AceOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1559, 439 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.AceOfClubs ) );
			CardsDictionary.Add( new Vector2( 1609, 439 ), Deck.PokerDeck( false ).Where( c => Suits.Clubs == c.Value.GetSuit() ) );

			CardsDictionary.Add( new Vector2( 309, 489 ), Deck.PokerDeck( true ).Where( c => new[] { CardValue.BigJoker, CardValue.LittleJoker, CardValue.TwoOfHearts, CardValue.TwoOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 359, 489 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.TwoOfHearts, CardValue.TwoOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 409, 489 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.TwoOfHearts, CardValue.TwoOfClubs, CardValue.ThreeOfHearts, CardValue.ThreeOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 459, 489 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.ThreeOfHearts, CardValue.ThreeOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 509, 489 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.ThreeOfHearts, CardValue.ThreeOfClubs, CardValue.FourOfHearts, CardValue.FourOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 559, 489 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.FourOfHearts, CardValue.FourOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 609, 489 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.FourOfHearts, CardValue.FourOfClubs, CardValue.FiveOfHearts, CardValue.FiveOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 659, 489 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.FiveOfHearts, CardValue.FiveOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 709, 489 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.FiveOfHearts, CardValue.FiveOfClubs, CardValue.SixOfHearts, CardValue.SixOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 759, 489 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.SixOfHearts, CardValue.SixOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 809, 489 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.SixOfHearts, CardValue.SixOfClubs, CardValue.SevenOfHearts, CardValue.SevenOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 859, 489 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.SevenOfHearts, CardValue.SevenOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 909, 489 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.SevenOfHearts, CardValue.SevenOfClubs, CardValue.EightOfHearts, CardValue.EightOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 959, 489 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.EightOfHearts, CardValue.EightOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1009, 489 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.EightOfHearts, CardValue.EightOfClubs, CardValue.NineOfHearts, CardValue.NineOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1059, 489 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.NineOfHearts, CardValue.NineOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1109, 489 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.NineOfHearts, CardValue.NineOfClubs, CardValue.TenOfHearts, CardValue.TenOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1159, 489 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.TenOfHearts, CardValue.TenOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1209, 489 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.TenOfHearts, CardValue.TenOfClubs, CardValue.JackOfHearts, CardValue.JackOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1259, 489 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.JackOfHearts, CardValue.JackOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1309, 489 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.JackOfHearts, CardValue.JackOfClubs, CardValue.QueenOfHearts, CardValue.QueenOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1359, 489 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.QueenOfHearts, CardValue.QueenOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1409, 489 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.QueenOfHearts, CardValue.QueenOfClubs, CardValue.KingOfHearts, CardValue.KingOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1459, 489 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.KingOfHearts, CardValue.KingOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1509, 489 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.KingOfHearts, CardValue.KingOfClubs, CardValue.AceOfHearts, CardValue.AceOfClubs }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1559, 489 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.AceOfHearts, CardValue.AceOfClubs }.Contains( c.Value ) ) );

			CardsDictionary.Add( new Vector2( 309, 539 ), Deck.PokerDeck( true ).Where( c => new[] { CardValue.BigJoker, CardValue.TwoOfHearts }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 359, 539 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.TwoOfHearts ) );
			CardsDictionary.Add( new Vector2( 409, 539 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.TwoOfHearts, CardValue.ThreeOfHearts }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 459, 539 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.ThreeOfHearts ) );
			CardsDictionary.Add( new Vector2( 509, 539 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.ThreeOfHearts, CardValue.FourOfHearts }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 559, 539 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.FourOfHearts ) );
			CardsDictionary.Add( new Vector2( 609, 539 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.FourOfHearts, CardValue.FiveOfHearts }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 659, 539 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.FiveOfHearts ) );
			CardsDictionary.Add( new Vector2( 709, 539 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.FiveOfHearts, CardValue.SixOfHearts }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 759, 539 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.SixOfHearts ) );
			CardsDictionary.Add( new Vector2( 809, 539 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.SixOfHearts, CardValue.SevenOfHearts }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 859, 539 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.SevenOfHearts ) );
			CardsDictionary.Add( new Vector2( 909, 539 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.SevenOfHearts, CardValue.EightOfHearts }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 959, 539 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.EightOfHearts ) );
			CardsDictionary.Add( new Vector2( 1009, 539 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.EightOfHearts, CardValue.NineOfHearts }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1059, 539 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.NineOfHearts ) );
			CardsDictionary.Add( new Vector2( 1109, 539 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.NineOfHearts, CardValue.TenOfHearts }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1159, 539 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.TenOfHearts ) );
			CardsDictionary.Add( new Vector2( 1209, 539 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.TenOfHearts, CardValue.JackOfHearts }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1259, 539 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.JackOfHearts ) );
			CardsDictionary.Add( new Vector2( 1309, 539 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.JackOfHearts, CardValue.QueenOfHearts }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1359, 539 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.QueenOfHearts ) );
			CardsDictionary.Add( new Vector2( 1409, 539 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.QueenOfHearts, CardValue.KingOfHearts }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1459, 539 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.KingOfHearts ) );
			CardsDictionary.Add( new Vector2( 1509, 539 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.KingOfHearts, CardValue.AceOfHearts }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1559, 539 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.AceOfHearts ) );
			CardsDictionary.Add( new Vector2( 1609, 539 ), Deck.PokerDeck( false ).Where( c => Suits.Hearts == c.Value.GetSuit() ) );

			CardsDictionary.Add( new Vector2( 309, 589 ), Deck.PokerDeck( true ).Where( c => new[] { CardValue.LittleJoker, CardValue.TwoOfHearts, CardValue.TwoOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 359, 589 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.TwoOfHearts, CardValue.TwoOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 409, 589 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.TwoOfHearts, CardValue.TwoOfDiamonds, CardValue.ThreeOfHearts, CardValue.ThreeOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 459, 589 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.ThreeOfHearts, CardValue.ThreeOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 509, 589 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.ThreeOfHearts, CardValue.ThreeOfDiamonds, CardValue.FourOfHearts, CardValue.FourOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 559, 589 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.FourOfHearts, CardValue.FourOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 609, 589 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.FourOfHearts, CardValue.FourOfDiamonds, CardValue.FiveOfHearts, CardValue.FiveOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 659, 589 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.FiveOfHearts, CardValue.FiveOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 709, 589 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.FiveOfHearts, CardValue.FiveOfDiamonds, CardValue.SixOfHearts, CardValue.SixOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 759, 589 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.SixOfHearts, CardValue.SixOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 809, 589 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.SixOfHearts, CardValue.SixOfDiamonds, CardValue.SevenOfHearts, CardValue.SevenOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 859, 589 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.SevenOfHearts, CardValue.SevenOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 909, 589 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.SevenOfHearts, CardValue.SevenOfDiamonds, CardValue.EightOfHearts, CardValue.EightOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 959, 589 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.EightOfHearts, CardValue.EightOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1009, 589 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.EightOfHearts, CardValue.EightOfDiamonds, CardValue.NineOfHearts, CardValue.NineOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1059, 589 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.NineOfHearts, CardValue.NineOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1109, 589 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.NineOfHearts, CardValue.NineOfDiamonds, CardValue.TenOfHearts, CardValue.TenOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1159, 589 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.TenOfHearts, CardValue.TenOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1209, 589 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.TenOfHearts, CardValue.TenOfDiamonds, CardValue.JackOfHearts, CardValue.JackOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1259, 589 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.JackOfHearts, CardValue.JackOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1309, 589 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.JackOfHearts, CardValue.JackOfDiamonds, CardValue.QueenOfHearts, CardValue.QueenOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1359, 589 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.QueenOfHearts, CardValue.QueenOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1409, 589 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.QueenOfHearts, CardValue.QueenOfDiamonds, CardValue.KingOfHearts, CardValue.KingOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1459, 589 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.KingOfHearts, CardValue.KingOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1509, 589 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.KingOfHearts, CardValue.KingOfDiamonds, CardValue.AceOfHearts, CardValue.AceOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1559, 589 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.AceOfHearts, CardValue.AceOfDiamonds }.Contains( c.Value ) ) );

			CardsDictionary.Add( new Vector2( 309, 639 ), Deck.PokerDeck( true ).Where( c => new[] { CardValue.BigJoker, CardValue.TwoOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 359, 639 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.TwoOfDiamonds ) );
			CardsDictionary.Add( new Vector2( 409, 639 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.TwoOfDiamonds, CardValue.ThreeOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 459, 639 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.ThreeOfDiamonds ) );
			CardsDictionary.Add( new Vector2( 509, 639 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.ThreeOfDiamonds, CardValue.FourOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 559, 639 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.FourOfDiamonds ) );
			CardsDictionary.Add( new Vector2( 609, 639 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.FourOfDiamonds, CardValue.FiveOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 659, 639 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.FiveOfDiamonds ) );
			CardsDictionary.Add( new Vector2( 709, 639 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.FiveOfDiamonds, CardValue.SixOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 759, 639 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.SixOfDiamonds ) );
			CardsDictionary.Add( new Vector2( 809, 639 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.SixOfDiamonds, CardValue.SevenOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 859, 639 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.SevenOfDiamonds ) );
			CardsDictionary.Add( new Vector2( 909, 639 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.SevenOfDiamonds, CardValue.EightOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 959, 639 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.EightOfDiamonds ) );
			CardsDictionary.Add( new Vector2( 1009, 639 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.EightOfDiamonds, CardValue.NineOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1059, 639 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.NineOfDiamonds ) );
			CardsDictionary.Add( new Vector2( 1109, 639 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.NineOfDiamonds, CardValue.TenOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1159, 639 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.TenOfDiamonds ) );
			CardsDictionary.Add( new Vector2( 1209, 639 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.TenOfDiamonds, CardValue.JackOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1259, 639 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.JackOfDiamonds ) );
			CardsDictionary.Add( new Vector2( 1309, 639 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.JackOfDiamonds, CardValue.QueenOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1359, 639 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.QueenOfDiamonds ) );
			CardsDictionary.Add( new Vector2( 1409, 639 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.QueenOfDiamonds, CardValue.KingOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1459, 639 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.KingOfDiamonds ) );
			CardsDictionary.Add( new Vector2( 1509, 639 ), Deck.PokerDeck( false ).Where( c => new[] { CardValue.KingOfDiamonds, CardValue.AceOfDiamonds }.Contains( c.Value ) ) );
			CardsDictionary.Add( new Vector2( 1559, 639 ), Deck.PokerDeck( false ).Where( c => c.Value == CardValue.AceOfDiamonds ) );
			CardsDictionary.Add( new Vector2( 1609, 639 ), Deck.PokerDeck( false ).Where( c => Suits.Diamonds == c.Value.GetSuit() ) );

			CardsDictionary.Add( new Vector2( 359, 689 ), Deck.PokerDeck( false ).Where( c => Ranks.Two == c.Value.GetRank() ) );
			CardsDictionary.Add( new Vector2( 409, 689 ), Deck.PokerDeck( false ).Where( c => new[] { Ranks.Two, Ranks.Three }.Contains( c.Value.GetRank() ) ) );
			CardsDictionary.Add( new Vector2( 459, 689 ), Deck.PokerDeck( false ).Where( c => Ranks.Three == c.Value.GetRank() ) );
			CardsDictionary.Add( new Vector2( 509, 689 ), Deck.PokerDeck( false ).Where( c => new[] { Ranks.Three, Ranks.Four }.Contains( c.Value.GetRank() ) ) );
			CardsDictionary.Add( new Vector2( 559, 689 ), Deck.PokerDeck( false ).Where( c => Ranks.Four == c.Value.GetRank() ) );
			CardsDictionary.Add( new Vector2( 609, 689 ), Deck.PokerDeck( false ).Where( c => new[] { Ranks.Four, Ranks.Five }.Contains( c.Value.GetRank() ) ) );
			CardsDictionary.Add( new Vector2( 659, 689 ), Deck.PokerDeck( false ).Where( c => Ranks.Five == c.Value.GetRank() ) );
			CardsDictionary.Add( new Vector2( 709, 689 ), Deck.PokerDeck( false ).Where( c => new[] { Ranks.Five, Ranks.Six }.Contains( c.Value.GetRank() ) ) );
			CardsDictionary.Add( new Vector2( 759, 689 ), Deck.PokerDeck( false ).Where( c => Ranks.Six == c.Value.GetRank() ) );
			CardsDictionary.Add( new Vector2( 809, 689 ), Deck.PokerDeck( false ).Where( c => new[] { Ranks.Six, Ranks.Seven }.Contains( c.Value.GetRank() ) ) );
			CardsDictionary.Add( new Vector2( 859, 689 ), Deck.PokerDeck( false ).Where( c => Ranks.Seven == c.Value.GetRank() ) );
			CardsDictionary.Add( new Vector2( 909, 689 ), Deck.PokerDeck( false ).Where( c => new[] { Ranks.Seven, Ranks.Eight }.Contains( c.Value.GetRank() ) ) );
			CardsDictionary.Add( new Vector2( 959, 689 ), Deck.PokerDeck( false ).Where( c => Ranks.Eight == c.Value.GetRank() ) );
			CardsDictionary.Add( new Vector2( 1009, 689 ), Deck.PokerDeck( false ).Where( c => new[] { Ranks.Eight, Ranks.Nine }.Contains( c.Value.GetRank() ) ) );
			CardsDictionary.Add( new Vector2( 1059, 689 ), Deck.PokerDeck( false ).Where( c => Ranks.Nine == c.Value.GetRank() ) );
			CardsDictionary.Add( new Vector2( 1109, 689 ), Deck.PokerDeck( false ).Where( c => new[] { Ranks.Nine, Ranks.Ten }.Contains( c.Value.GetRank() ) ) );
			CardsDictionary.Add( new Vector2( 1159, 689 ), Deck.PokerDeck( false ).Where( c => Ranks.Ten == c.Value.GetRank() ) );
			CardsDictionary.Add( new Vector2( 1209, 689 ), Deck.PokerDeck( false ).Where( c => new[] { Ranks.Ten, Ranks.Jack }.Contains( c.Value.GetRank() ) ) );
			CardsDictionary.Add( new Vector2( 1259, 689 ), Deck.PokerDeck( false ).Where( c => Ranks.Jack == c.Value.GetRank() ) );
			CardsDictionary.Add( new Vector2( 1309, 689 ), Deck.PokerDeck( false ).Where( c => new[] { Ranks.Jack, Ranks.Queen }.Contains( c.Value.GetRank() ) ) );
			CardsDictionary.Add( new Vector2( 1359, 689 ), Deck.PokerDeck( false ).Where( c => Ranks.Queen == c.Value.GetRank() ) );
			CardsDictionary.Add( new Vector2( 1409, 689 ), Deck.PokerDeck( false ).Where( c => new[] { Ranks.Queen, Ranks.King }.Contains( c.Value.GetRank() ) ) );
			CardsDictionary.Add( new Vector2( 1459, 689 ), Deck.PokerDeck( false ).Where( c => Ranks.King == c.Value.GetRank() ) );
			CardsDictionary.Add( new Vector2( 1509, 689 ), Deck.PokerDeck( false ).Where( c => new[] { Ranks.King, Ranks.Ace }.Contains( c.Value.GetRank() ) ) );
			CardsDictionary.Add( new Vector2( 1559, 689 ), Deck.PokerDeck( false ).Where( c => Ranks.Ace == c.Value.GetRank() ) );

			CardsDictionary.Add( new Vector2( 259, 389 ), Deck.PokerDeck( true ).Where( c => c.Value == CardValue.BigJoker ) );
			CardsDictionary.Add( new Vector2( 259, 489 ), Deck.PokerDeck( true ).Where( c => Suits.Joker == c.Value.GetSuit() ) );
			CardsDictionary.Add( new Vector2( 259, 589 ), Deck.PokerDeck( true ).Where( c => c.Value == CardValue.LittleJoker ) );
			CardsDictionary.Add( new Vector2( 1659, 389 ), Deck.PokerDeck( false ).Where( c => new[] { Suits.Clubs, Suits.Spades }.Contains( c.Value.GetSuit() ) ) );
			CardsDictionary.Add( new Vector2( 1659, 589 ), Deck.PokerDeck( false ).Where( c => new[] { Suits.Hearts, Suits.Diamonds }.Contains( c.Value.GetSuit() ) ) );
			CardsDictionary.Add( new Vector2( 509, 739 ), Deck.PokerDeck( false ).Where( c => new[] { Ranks.Two, Ranks.Three, Ranks.Four, Ranks.Five }.Contains( c.Value.GetRank() ) ) );
			CardsDictionary.Add( new Vector2( 959, 739 ), Deck.PokerDeck( false ).Where( c => new[] { Ranks.Six, Ranks.Seven, Ranks.Eight, Ranks.Nine, Ranks.Ten }.Contains( c.Value.GetRank() ) ) );
			CardsDictionary.Add( new Vector2( 1409, 739 ), Deck.PokerDeck( false ).Where( c => new[] { Ranks.Jack, Ranks.Queen, Ranks.King, Ranks.Ace }.Contains( c.Value.GetRank() ) ) );
		}

		private static void FillBetTypes() {
			BetTypesDictionary.Add( new Vector2( 309, 339 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 359, 339 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 409, 339 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 459, 339 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 509, 339 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 559, 339 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 609, 339 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 659, 339 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 709, 339 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 759, 339 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 809, 339 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 859, 339 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 909, 339 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 959, 339 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1009, 339 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1059, 339 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1109, 339 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1159, 339 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1209, 339 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1259, 339 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1309, 339 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1359, 339 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1409, 339 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1459, 339 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1509, 339 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1559, 339 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1609, 339 ), BetType.Spades );

			BetTypesDictionary.Add( new Vector2( 309, 389 ), BetType.TripleCard );
			BetTypesDictionary.Add( new Vector2( 359, 389 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 409, 389 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 459, 389 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 509, 389 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 559, 389 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 609, 389 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 659, 389 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 709, 389 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 759, 389 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 809, 389 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 859, 389 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 909, 389 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 959, 389 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1009, 389 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 1059, 389 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1109, 389 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 1159, 389 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1209, 389 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 1259, 389 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1309, 389 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 1359, 389 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1409, 389 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 1459, 389 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1509, 389 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 1559, 389 ), BetType.DoubleCard );

			BetTypesDictionary.Add( new Vector2( 309, 439 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 359, 439 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 409, 439 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 459, 439 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 509, 439 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 559, 439 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 609, 439 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 659, 439 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 709, 439 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 759, 439 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 809, 439 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 859, 439 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 909, 439 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 959, 439 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1009, 439 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1059, 439 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1109, 439 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1159, 439 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1209, 439 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1259, 439 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1309, 439 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1359, 439 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1409, 439 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1459, 439 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1509, 439 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1559, 439 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1609, 439 ), BetType.Clubs );

			BetTypesDictionary.Add( new Vector2( 309, 489 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 359, 489 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 409, 489 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 459, 489 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 509, 489 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 559, 489 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 609, 489 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 659, 489 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 709, 489 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 759, 489 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 809, 489 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 859, 489 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 909, 489 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 959, 489 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1009, 489 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 1059, 489 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1109, 489 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 1159, 489 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1209, 489 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 1259, 489 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1309, 489 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 1359, 489 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1409, 489 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 1459, 489 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1509, 489 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 1559, 489 ), BetType.DoubleCard );

			BetTypesDictionary.Add( new Vector2( 309, 539 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 359, 539 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 409, 539 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 459, 539 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 509, 539 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 559, 539 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 609, 539 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 659, 539 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 709, 539 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 759, 539 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 809, 539 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 859, 539 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 909, 539 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 959, 539 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1009, 539 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1059, 539 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1109, 539 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1159, 539 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1209, 539 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1259, 539 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1309, 539 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1359, 539 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1409, 539 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1459, 539 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1509, 539 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1559, 539 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1609, 539 ), BetType.Hearts );

			BetTypesDictionary.Add( new Vector2( 309, 589 ), BetType.TripleCard );
			BetTypesDictionary.Add( new Vector2( 359, 589 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 409, 589 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 459, 589 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 509, 589 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 559, 589 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 609, 589 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 659, 589 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 709, 589 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 759, 589 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 809, 589 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 859, 589 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 909, 589 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 959, 589 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1009, 589 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 1059, 589 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1109, 589 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 1159, 589 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1209, 589 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 1259, 589 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1309, 589 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 1359, 589 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1409, 589 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 1459, 589 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1509, 589 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 1559, 589 ), BetType.DoubleCard );

			BetTypesDictionary.Add( new Vector2( 309, 639 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 359, 639 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 409, 639 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 459, 639 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 509, 639 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 559, 639 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 609, 639 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 659, 639 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 709, 639 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 759, 639 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 809, 639 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 859, 639 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 909, 639 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 959, 639 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1009, 639 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1059, 639 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1109, 639 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1159, 639 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1209, 639 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1259, 639 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1309, 639 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1359, 639 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1409, 639 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1459, 639 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1509, 639 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 1559, 639 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1609, 639 ), BetType.Diamonds );

			BetTypesDictionary.Add( new Vector2( 359, 689 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 409, 689 ), BetType.OctCard );
			BetTypesDictionary.Add( new Vector2( 459, 689 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 509, 689 ), BetType.OctCard );
			BetTypesDictionary.Add( new Vector2( 559, 689 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 609, 689 ), BetType.OctCard );
			BetTypesDictionary.Add( new Vector2( 659, 689 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 709, 689 ), BetType.OctCard );
			BetTypesDictionary.Add( new Vector2( 759, 689 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 809, 689 ), BetType.OctCard );
			BetTypesDictionary.Add( new Vector2( 859, 689 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 909, 689 ), BetType.OctCard );
			BetTypesDictionary.Add( new Vector2( 959, 689 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 1009, 689 ), BetType.OctCard );
			BetTypesDictionary.Add( new Vector2( 1059, 689 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 1109, 689 ), BetType.OctCard );
			BetTypesDictionary.Add( new Vector2( 1159, 689 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 1209, 689 ), BetType.OctCard );
			BetTypesDictionary.Add( new Vector2( 1259, 689 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 1309, 689 ), BetType.OctCard );
			BetTypesDictionary.Add( new Vector2( 1359, 689 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 1409, 689 ), BetType.OctCard );
			BetTypesDictionary.Add( new Vector2( 1459, 689 ), BetType.QuadCard );
			BetTypesDictionary.Add( new Vector2( 1509, 689 ), BetType.OctCard );
			BetTypesDictionary.Add( new Vector2( 1559, 689 ), BetType.QuadCard );

			BetTypesDictionary.Add( new Vector2( 259, 389 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 259, 489 ), BetType.DoubleCard );
			BetTypesDictionary.Add( new Vector2( 259, 589 ), BetType.SingleCard );
			BetTypesDictionary.Add( new Vector2( 1659, 389 ), BetType.Black );
			BetTypesDictionary.Add( new Vector2( 1659, 589 ), BetType.Red );
			BetTypesDictionary.Add( new Vector2( 509, 739 ), BetType.Low );
			BetTypesDictionary.Add( new Vector2( 959, 739 ), BetType.Mid );
			BetTypesDictionary.Add( new Vector2( 1409, 739 ), BetType.High );
		}

		private static readonly IDictionary<Vector2,BetType> BetTypesDictionary;
		private static readonly IDictionary<Vector2,IEnumerable<Card>> CardsDictionary;
	}
}
